version: 2

project_name: tdd-ai

before:
  hooks:
    - go mod tidy

builds:
  - binary: tdd-ai
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/macosta/tdd-ai/cmd.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
